#!/usr/bin/env ruby
require 'sinatra/strap'

s = Sinatra::Strap::Base.new

if ARGV[0] == "new"
  unless (appname=ARGV[1]) == nil 
    s.appname = appname
    s.generate
    s.replace
  end
else 
  s.show_help
end

